### ISSUE TITLE
API - Urgent Security Bug: tj-actions GitHub Action is compromised

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#3367]
**Describe the bug**
1. The `tj-actions` GitHub Action is compromised and the GitHub action repository has been deleted.
1. This is causing many of our GitHub actions to fail

Advisory notifications:

1. https://github.com/advisories/GHSA-mcph-m25j-8j63
1. https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
1. https://news.ycombinator.com/item?id=43367987
1. https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
1. https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066l

**Expected Outcome**

1. Find a reliable alternative to tj-actions which reference `steps.changed-files` and `steps.changed_files` in the GitHub action files
1. Update the GitHub action files to use the new methodology
1. No functionality of the GitHub actions must be altered

**Reference Issues**

1. https://github.com/PalisadoesFoundation/talawa-api/issues/3367
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/3851
1. https://github.com/PalisadoesFoundation/talawa/issues/2783
3. https://github.com/PalisadoesFoundation/talawa-docs/issues/981
2. https://github.com/PalisadoesFoundation/switchmap-ng/issues/303
4. https://github.com/PalisadoesFoundation/switchmap-ng-docs/issues/27

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@adithyanotfound

**Comment by adithyanotfound** [comment]
Should I update them in PR #3366 itself or create separate PR for this issue?

**Comment by rahulch07** [comment]
please assign

**Comment by palisadoes** [comment]
@adithyanotfound Please create a separate PR. It'll be faster
@rahulch07 had some suggestions in this thread:
- https://github.com/PalisadoesFoundation/talawa-api/pull/3366#issuecomment-2726913755

**Comment by rahulch07** [comment]
@adithyanotfound you can replace with this code. it gets the name of change files and stores in files environment variable in github actions workflow.

```
python_checks:
    name: Run Python Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin develop-postgres
          echo "files=$(git diff --name-only origin/develop-postgres)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Run Biome Ignore Check
        run: |
          python .github/workflows/scripts/biome_disable_check.py --files ${{ env.files }}

      - name: Run Code Coverage Disable Check
        run: |
          python .github/workflows/scripts/code_coverage_disable_check.py --files ${{ env.files }}

      - name: Run TS Ignore Check
        run: |
          python .github/workflows/scripts/detect_ts_ignore.py --files ${{ env.files }}
```
